#!/bin/sh
uci set luci.themes.@luci-theme-lumos[0].name=LumOS
uci set luci.themes.@luci-theme-lumos[0].mediaurlbase=/luci-static/lumos
uci set luci.main.mediaurlbase=/luci-static/lumos
uci commit luci
exit 0